<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>tpanda.maven.plugins.it</groupId>
    <artifactId>dependency-it</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>dependency-exe-it</artifactId>
  <packaging>gcc-exe</packaging>

  <description>依存関係のテスト(依存する側)</description>

  <properties>
  </properties>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>dependency-dll-it</artifactId>
      <version>${project.version}</version>
      <scope>runtime</scope>
      <type>dll</type>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>dependency-dll-it</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
      <classifier>imp-lib</classifier>
      <type>dll.a</type>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>dependency-dll-it</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
      <classifier>headers</classifier>
      <type>zip</type>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>@project.groupId@</groupId>
        <artifactId>@project.artifactId@</artifactId>
        <version>@project.version@</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
</project>
